import type { IconName } from './Icon';

/**
 * The classic skin's desktop icons, as text.
 *
 * One character per pixel, 32 rows of 32, a sixteen-colour palette — which is what a desktop icon
 * of the era was, and a format that can be read, reviewed and corrected in a diff without an image
 * editor. `PixelIcon.tsx` rasterises these to crisp SVG at render time.
 *
 * They are original drawings of generic objects — a folder, a magnifier, a sheet of paper, a
 * framed picture — in the idiom of the period: a black outline, light from the top left, a darker
 * shade on the bottom and right. No vendor's artwork is reproduced (ADR 1).
 *
 * Legend: . transparent  k black  w white  g grey  d dark grey  n navy  b blue  t teal  c cyan
 *         G green  l lime  m maroon  r red  o olive  y yellow  p purple  M magenta
 */

export const PIXEL_SIZE = 32;

export const PIXEL_PALETTE = {
  k: '#000000',
  w: '#ffffff',
  g: '#c0c0c0',
  d: '#808080',
  n: '#000080',
  b: '#0000ff',
  t: '#008080',
  c: '#00ffff',
  G: '#008000',
  l: '#00ff00',
  m: '#800000',
  r: '#ff0000',
  o: '#808000',
  y: '#ffff00',
  p: '#800080',
  M: '#ff00ff',
} as const;

export type PixelKey = keyof typeof PIXEL_PALETTE;

export const PIXEL_ART: Partial<Record<IconName, string>> = {
  folder: `
................................
................................
................................
................................
.kkkkkkkkkkkk...................
.kyyyyyyyyyyk...................
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
.kooooooooooooooooooooooooooook.
.kooooooooooooooooooooooooooook.
.kooooooooooooooooooooooooooook.
.kooooooooooooooooooooooooooook.
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
.kwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwyyyyyyyyyyyyyyyyyyyyyyyyyyok.
.kwoooooooooooooooooooooooooook.
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
................................
................................
................................
................................
................................
`,
  search: `
................................
................................
................................
..........kkkkk.................
........kkccccckk...............
......kkccccccccckk.............
.....kkccccccccccckk............
.....kccwwwcccccccck............
....kccwwwwwcccccccck...........
....kccwwwwwcccccccck...........
...kcccwwwwwccccccccck..........
...kccccwwwcccccccccck..........
...kccccccccccccccccck..........
...kccccccccccccccccck..........
...kccccccccccccccccck..........
....kccccccccccccccck...........
....kccccccccccccccck...........
.....kccccccccccccck............
.....kkccccccccccckkkkk.........
......kkccccccccckkkkkkk........
........kkccccckk.kkdddkk.......
..........kkkkk...kkddddkk......
..................kkdddddkk.....
...................kkdddddkk....
....................kkdddddkk...
.....................kkdddddkk..
......................kkdddddkk.
.......................kkdddddk.
........................kkddddk.
.........................kkdddk.
..........................kkkkk.
................................
`,
  note: `
................................
................................
................................
......kkkkkkkkkkkkkkkkkkkk......
......kddddddddddddddddddk......
......kddkdddkdddkdddkdddk......
......kddddddddddddddddddk......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyrybbbbbbbbbbbyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyrybbbbbbbbbbbyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyrybbbbbbbbbbbyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyrybbbbbbbbbbbyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyryyyyyyyyyyyyyok......
......kyyyrybbbbbbbbbbbyok......
......kooooooooooooooooook......
......kkkkkkkkkkkkkkkkkkkk......
................................
................................
`,
  'file-text': `
................................
................................
................................
.......kkkkkkkkkkkkk............
.......kwwwwwwwwwwwkk...........
.......kwwwwwwwwwwwkgk..........
.......kwwwwwwwwwwwkggk.........
.......kwwwwwwwwwwwkgggk........
.......kwwwwwwwwwwwkkkkkk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwddddddddddddwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwddddddddddwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwddddddddddddwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwddddddddwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwdddddddddddwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kwwwwwwwwwwwwwwwdk.......
.......kddddddddddddddddk.......
.......kkkkkkkkkkkkkkkkkk.......
................................
................................
`,
  image: `
................................
................................
................................
................................
................................
..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
..kwwwwwwwwwwwwwwwwwwwwwwwwwdk..
..kwggggggggggggggggggggggggdk..
..kwgkkkkkkkkkkkkkkkkkkkkkkgdk..
..kwgkcccccccccccccccccccckgdk..
..kwgkccccyyyccccccccccccckgdk..
..kwgkcccyyyyycccccccccccckgdk..
..kwgkccyyyyyyyccccGcccccckgdk..
..kwgkccyyyyyyycccGGGccccckgdk..
..kwgkccyyyyyyyccGGGGGcccckgdk..
..kwgkcccyyyyyccGGGGGGGccckgdk..
..kwgkccccyyyccGGGGGGGGGcckgdk..
..kwgkccccccccGGGGGGGGGGGckgdk..
..kwgkcccccccGGGGGGGGGGGGGkgdk..
..kwgklGlGlGlGlGlGlGlGlGlGkgdk..
..kwgkGGGGGGGGGGGGGGGGGGGGkgdk..
..kwgkGGGGGGGGGGGGGGGGGGGGkgdk..
..kwgkGGGGGGGGGGGGGGGGGGGGkgdk..
..kwgkkkkkkkkkkkkkkkkkkkkkkgdk..
..kwggggggggggggggggggggggggdk..
..kddddddddddddddddddddddddddk..
..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
................................
................................
................................
................................
................................
`,
  music: `
................................
................................
................................
................................
................................
...................k............
..................kk....k.......
.................kgk.....k......
................kgdk......kk....
...............kgddk...k...k....
..............kgdddk....k...k...
.............kgddddk.....k...k..
....kkkkkkkkkgdddddk..k...k..k..
....kwwwwwdkgddddddk...k..k...k.
....kwggggdddddddddk....k..k..k.
....kwggggdddddddddk....k..k..k.
....kwggggdddddddddk....k..k..k.
....kwggggdddddddddk....k..k..k.
....kddddddkdddddddk....k..k..k.
....kkkkkkkkkddddddk...k..k...k.
.............kdddddk..k...k..k..
..............kddddk.....k...k..
...............kdddk....k...k...
................kddk...k...k....
.................kdk......kk....
..................kk.....k......
...................k....k.......
................................
................................
................................
................................
................................
`,
  video: `
................................
................................
................................
................................
................................
................................
................................
..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
..kkwwkkwwkkwwkkwwkkwwkkwwkkkk..
..kkwwkkwwkkwwkkwwkkwwkkwwkkkk..
..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
..kkkcccccccccckkcccccccccckkk..
..kkkcccccccccckkcccccccccckkk..
..kkkcccycccccckkcccycccccckkk..
..kkkccyyyccccckkccyyyccccckkk..
..kkkcccycccccckkcccycccccckkk..
..kkkcccccccccckkcccccccccckkk..
..kkkGlGlGlGlGlkkGlGlGlGlGlkkk..
..kkkGGGGGGGGGGkkGGGGGGGGGGkkk..
..kkkGGGGGGGGGGkkGGGGGGGGGGkkk..
..kkkGGGGGGGGGGkkGGGGGGGGGGkkk..
..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
..kkwwkkwwkkwwkkwwkkwwkkwwkkkk..
..kkwwkkwwkkwwkkwwkkwwkkwwkkkk..
..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
................................
................................
................................
................................
................................
................................
................................
`,
  link: `
................................
................................
................................
................................
................................
................................
...........kkkkkkkkkk...........
...........kmmmmmmmmk...........
...........kmkkkkkkmk...........
...........km......mk...........
...kkkkkkkkkkkkkkkkkkkkkkkkkk...
...krrrrrrrrrrrrrrrrrrrrrrrrk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmkkkkkkmmmmmmmmkk...
...kkkkkkkkkkkyyyykkkkkkkkkkk...
...krmmmmmmmmkyyyykmmmmmmmmkk...
...krmmmmmmmmkkkkkkmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krmmmmmmmmmmmmmmmmmmmmmmkk...
...krkkkkkkkkkkkkkkkkkkkkkkkk...
...kkkkkkkkkkkkkkkkkkkkkkkkkk...
................................
................................
................................
................................
`,
  gauge: `
................................
................................
................................
...kkkkkkkkkkkkkkkkkkkkkkkkkk...
...kwwwwwwwwwwwwwwwwwwwwwwwdk...
...kwggggggggggggggggggggggdk...
...kwgkkkkkkkkkkkkkkkkkkkkgdk...
...kwgkkkkkkkkkkkkkkkkkkkkgdk...
...kwgkkkkkkkkkkkkkkkkkkkkgdk...
...kwgkkkkkkkkkkklkkkkkkkkgdk...
...kwgkkkkkkkkkkkllkkkklkkgdk...
...kwgkkkkkkkkkklkklkklkkkgdk...
...kwgkkkkklkkkklkklklkkkkgdk...
...kwgkkkklklkklkkkklkkkkkgdk...
...kwgkkkklkklklkkkkkkkkkkgdk...
...kwgkkklkkkklkkkkkkkkkkkgdk...
...kwgkklkkkkkkkkkkkkkkkkkgdk...
...kwgkkkkkkkkkkkkkkkkkkkkgdk...
...kwgkkkkkkkkkkkkkkkkkkkkgdk...
...kwgkkkkkkkkkkkkkkkkkkkkgdk...
...kwggggggggggggggggggggggdk...
...kddddddddddddddddddddddddk...
...kkkkkkkkkkkkkkkkkkkkkkkkkk...
.............dddddd.............
.............dddddd.............
........kkkkkkkkkkkkkkkk........
........kggggggggggggggk........
........kkkkkkkkkkkkkkkk........
................................
................................
................................
................................
`,
  apps: `
................................
................................
................................
................................
...kkkkkkkkkkkkkkkkkkkkkkkkkk...
...kwwwwwwwwwwwwwwwwwwwwwwwdk...
...kwnnnnnnnnnnnnnnnnnnnnnndk...
...kwnwwwwwwwnnnnnnnnnnnggndk...
...kwnwwwwwwwnnnnnnnnnnngdndk...
...kwnnnnnnnnnnnnnnnnnnnnnndk...
...kwggggggggggggggggggggggdk...
...kwggggggggggggggggggggggdk...
...kwggggggggggggggggggggggdk...
...kwggggggggggggggggggggggdk...
...kwggggggggggggggggggggggdk...
...kwggggkkkkkkkkkkkkkkggggdk...
...kwggggkwwwwwwwwwwwdkggggdk...
...kwggggkwgddddddddgdkggggdk...
...kwggggkwgddddddddgdkggggdk...
...kwggggkddddddddddddkggggdk...
...kwggggkkkkkkkkkkkkkkggggdk...
...kwggggggggggggggggggggggdk...
...kwggggggggggggggggggggggdk...
...kwggggggggggggggggggggggdk...
...kwggggggggggggggggggggggdk...
...kddddddddddddddddddddddddk...
...kkkkkkkkkkkkkkkkkkkkkkkkkk...
................................
................................
................................
................................
................................
`,
  settings: `
................................
................................
................................
.............kkkkk..............
.............kgggk..............
.............kgggk..............
......kkkkk..kgggkk..kkkkk......
......kgggk.kkwwwwwkkkgggk......
......kgggkkwwgggggwwkgggk......
......kgggwwgggggggggwwggk......
......kkkwgggggggggggggdkk......
........kwgggggggggggggdk.......
.......kwggggggkkkggggggdk......
.......kwggggkkdddkkggggdk......
...kkkkwgggggkdddddkgggggdkkkk..
...kgggwggggkdddddddkggggdgggk..
...kgggwggggkdddddddkggggdgggk..
...kgggwggggkdddddddkggggdgggk..
...kkkkwgggggkdddddkgggggdkkkk..
.......kwggggkkdddkkggggdk......
.......kwggggggkkkggggggdk......
......kkkwgggggggggggggdkk......
......kggwgggggggggggggdgk......
......kgggddgggggggggddggk......
......kgggkkddgggggddkgggk......
......kkkkk.kkdddddkkkkkkk......
..............kgggk.............
..............kgggk.............
..............kgggk.............
..............kkkkk.............
................................
................................
`,
  info: `
................................
................................
................................
..............kkkkk.............
...........kkkbbbbbkkk..........
.........kkbbcccccccbbkk........
........kbbccbbbbbbbbbbbk.......
.......kbbcbbbbbbbbbbbbbbk......
......kbccbbbbbwwwbbbbbbbbk.....
.....kbbcbbbbbbwwwbbbbbbbbbk....
.....kbcbbbbbbbwwwbbbbbbbbbk....
....kbcbbbbbbbbbbbbbbbbbbbbbk...
....kbcbbbbbbbbbbbbbbbbbbbbbk...
....kcbbbbbbbbwwwwbbbbbbbbbnk...
...kbcbbbbbbbbbwwwbbbbbbbbbnbk..
...kbcbbbbbbbbbwwwbbbbbbbbbnbk..
...kbcbbbbbbbbbwwwbbbbbbbbbnbk..
...kbcbbbbbbbbbwwwbbbbbbbbbnbk..
...kbcbbbbbbbbbwwwbbbbbbbbbnbk..
....kcbbbbbbbbbwwwbbbbbbbbbnk...
....kbbbbbbbbbbwwwbbbbbbbbnbk...
....kbbbbbbbbbbwwwbbbbbbbbnbk...
.....kbbbbbbbbwwwwwbbbbbbnbk....
.....kbbbbbbbbbbbbbbbbbbnbbk....
......kbbbbbbbbbbbbbbbbnnbk.....
.......kbbbbbbbbbbbbbbnbbk......
........kbbbbbbbbbbbnnbbk.......
.........kkbbnnnnnnnbbkk........
...........kkkbbbbbkkk..........
..............kkkkk.............
................................
................................
`,
};
